

import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";import AuthButtons from "@/components/auth-buttons";
;


/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

const rubikSans = localFont({
  src: "./fonts/Rubik-Var.ttf",
  variable: "--font-rubik-sans",
});

const rubikItalic = localFont({
  src: "./fonts/Rubik-Italic-Var.ttf",
  variable: "--font-rubik-italic",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${rubikSans.variable} ${rubikItalic.variable} antialiased`}
      >
        <nav className="bg-purple-700 text-white p-5 h-24 flex items-center justify-between z-10 relative">
          <Link href="/marketMain" className="text-3xl tracking-widest flex gap-2 items-center uppercase">
            <span>Campus marketplace</span>
          </Link>        
          <ul className="flex gap-6 items-center">
            <li>
              <AuthButtons children={children}/> {/* Pass children down to AuthButtons component*/}
            </li>              
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
