# .github/workflows/deploy-development-channel.yml
name: Deploy to Development Channel on PR Merge

on:
  pull_request:
    types: [closed] # Only trigger when a pull request is closed (merged or not)

jobs:
  build_and_deploy_development:
    # Only run this job if the pull request was merged AND its base branch was 'development'
    if: ${{ github.event.pull_request.merged == true && github.base_ref == 'refs/heads/development' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ensure this matches your Next.js project's Node.js version
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js App
        run: npm run build

      - name: Deploy to Firebase Development Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAMPUS_MARKET_PLACE_3F978 }}'
          projectId: campus-marketplace-c7d92
          channelId: development # This will be your persistent 'development' channel
          expires: never # Set this channel to never expire if you want it to be permanent
